### ISSUE TITLE
Tasks boiling down: Data collection for BEVFusion in Carla

### ISSUE THREAD

**Issue by LittleBlackCQ** [little-black-sjtu/Lidar-Data-Generator#1]
### Part I: Preparation
- [x] Decide the positions, parameters and calibrations of five cameras.
- [x] Select a map, setup the vehicles, and finish the initialization of data collection.
- [ ] Decide the map ground truth: the size of it in realistic world, how many pixels it has.

### Part II: Problems to Solve
- [ ] How to record the zebra-crossing and curb in an object-like form.
- [ ] How to record curb in the semantic form.

### Part III: Code Development
- [x] Support camera.
- [x] Add pedestrians.
- [x] Transform the 3D object bounding box and project it onto the image plane.
- [ ] Transform data to NuScenes-like structure.
